resource_types:
- name: telegram
  type: docker-image
  source:
    repository: carlocolombo/telegram-resource

resources:
- name: telegram2
  type: telegram
  source:
    filter: task2
    telegram_key: {{telegram_bot_token}}
- name: telegram1
  type: telegram
  source:
    #filter: task1
    telegram_key: {{telegram_bot_token}}
- name: git-tasks
  type: git
  source:
    uri: https://gist.github.com/5d13889c5e7e6ce7d102dfd9189ee325.git
    branch: master

jobs:
- name: test-task
  plan:
  - get: telegram1
    trigger: true
  - get: git-tasks
  - task: read-message
    file: git-tasks/read-message.yml
  - put: telegram2
    params:
      chat_id: telegram2/chat_id
      text: telegram2/text
- name: test-task2
  plan:
  - get: telegram2
    trigger: true
  - get: git-tasks
  - task: read-message
    file: git-tasks/prepare-message.yml
  - put: telegram1
    params:
      chat_id: telegram1/chat_id
      text: telegram1/text
