resource_types:
- name: telegram
  type: docker-image
  source:
    repository: carlocolombo/telegram-resource
    tag: latest-dev

resources:
- name: start
  check_every: 5s
  type: telegram
  source:
    filter: '/start'
    telegram_key: {{telegram_bot_token}}
- name: answer
  type: telegram
  source:
    telegram_key: {{telegram_bot_token}}
- name: release
  check_every: 5s
  type: telegram
  source:
    filter: 'make_release'
    telegram_key: {{telegram_bot_token}}

task_resource: &task_resource
  type: docker-image
  source:
    repository: concourse/buildroot
    tag: 'curl'

jobs:
- name: send /start
  plan:
  - get: start
    trigger: true
  - task: prepare-answer
    config:
      platform: linux
      image_resource: *task_resource
      inputs:
      - name: start
      outputs:
      - name: answer
      run:
        path: sh
        args:
        - -exc
        - |
          jq '{chat_id: .chat.id, text: "hello", reply_markup:{keyboard:[[{text: "make_release"}],[{text: "make_product"}]]}}' < start/message > answer/message
          echo "Your chat id is \`$(cat answer/chat_id)\`" > answer/text
          jq . < answer/message
  - put: answer
    params:
      message: answer/message

- name: make release
  plan:
  - get: release
    trigger: true
  - task: test-code
    config:
      platform: linux
      image_resource: *task_resource
      inputs:
      - name: release
      run:
        path: sh
        args:
        - -exc
        - |
          jq . < release/message
