resource_types:
- name: telegram
  type: docker-image
  source:
    repository: carlocolombo/telegram-resource
    tag: latest-dev

resources:
- name: start
  check_every: 5s
  type: telegram
  source:
    filter: '/start'
    telegram_key: {{telegram_bot_token}}
- name: answer
  type: telegram
  source:
    telegram_key: {{telegram_bot_token}}

task_resource: &task_resource
  type: docker-image
  source:
    repository: concourse/buildroot
    tag: 'curl'

jobs:
- name: run-test
  plan:
  - get: start
    trigger: true
  - task: test-code
    config:
      platform: linux
      image_resource: *task_resource
      inputs:
      - name: start
      outputs:
      - name: answer
      run:
        path: sh
        args:
        - -exc
        - |
          jq .chat.id < start/message > answer/chat_id
          echo "Your chat id is $(cat answer/chat_id)" > answer/text
  - put: answer
    params:
      chat_id: answer/chat_id
      text: answer/text
